'use client'

import Head from 'next/head'

import { Providers } from './providers'

import '../styles/globals.css'

const Layout = ({ children }) => {
    return (
        <html lang='en'>
            <Head>
                <title>Administrator Laboratorium</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    )
}

export default Layout